### ISSUE TITLE
Hi Miroslav!

### ISSUE THREAD

**Issue by mkam039** [Miro-dev/Students#1]
My email address is on my home page (kamalov.net). Send me your CV.

**Comment by Miro-dev** [comment]
Hey,
Right now i am at work. Around 8pm I'll be home and I'll send it to you tonight. I will just need some time to fix some stuff here and there. Should I upload my projects to github and reference that in the CV?

**Comment by mkam039** [comment]
No rush. Take your time. It's a good idea to put your projects on github.
